tasks:
  - name: remove-label
    on:
      issue_comment:
        types: [created]
    config:
      label: 'needs reply'
      exclude-labeler: true
  - name: add-platform-labels
    on:
      issues:
        types: [opened, edited]
  - name: add-contributors
    on:
      push:
        branches: [main]
    config:
      base: main
      commit-message: 'chore(readme): add new contributor'
      exclude-pattern: '^(?!Ionitron).+?(?<!\\[bot\\])$'
