tasks:
  - name: add-label
    on:
      issues:
        types: [labeled]
    condition: 'payload.label.name == "needs reproduction"'
    config:
      label: 'needs reply'
  - name: remove-label
    on:
      issue_comment:
        types: [created]
    config:
      label: 'needs reply'
      exclude-labeler: true
  - name: add-contributors
    on:
      push:
        branches: [main]
    config:
      base: main
      commit-message: 'chore(readme): add new contributor'
      exclude-patterns:
        - '^Ionitron$'
        - '\[bot\]$'
