tasks:
  - name: add-comment
    on:
      issues:
        types: [labeled]
    condition: 'payload.label.name == "needs reproduction"'
    config:
      comment: |
        This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

        Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

        Thanks!
        Ionitron 💙
  - name: add-label
    on:
      issues:
        types: [labeled]
    condition: 'payload.label.name == "needs reproduction"'
    config:
      label: 'needs reply'
  - name: remove-label
    on:
      issue_comment:
        types: [created]
    config:
      label: 'needs reply'
      exclude-labeler: true
  - name: add-platform-labels
    on:
      issues:
        types: [opened, edited]
  - name: add-contributors
    on:
      push:
        branches: [main]
    config:
      base: main
      commit-message: 'chore(readme): add new contributor'
      exclude-patterns:
        - '^Ionitron$'
        - '\[bot\]$'
  - name: assign-to-project
    on:
      issues:
        types: [opened]
      pull_request:
        types: [opened]
    condition: (await getTeamMembers('capacitor')).includes(payload.sender.login)
    config:
      columns:
        issue: 10495656
        pr: 10495659
        draft-pr: 10495658
