triage:
  label: triage
  dryRun: false

lockClosed:
  days: 30
  maxIssuesPerRun: 100
  message: >
    Thanks for the issue! This issue is being locked to prevent comments that are not relevant to the original issue.
    If this is still an issue with the latest version of Capacitor, please create a new issue and ensure the template is fully filled out.
  dryRun: false

comment:
  labels:
    - label: "type: bug"
    message: >
      This issue has been labeled as `type: bug`. This label is added to issues
      that that have been reproduced and are being tracked in our internal issue tracker.
    - label: "needs reproduction"
    message: >
      This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

      Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

      Thanks!
      Ionitron 💙
    dryRun: false