triage:
  label: triage
  dryRun: false

lockClosed:
  days: 30
  maxIssuesPerRun: 100
  message: >
    Thanks for the issue! This issue is being locked to prevent comments that are not relevant to the original issue.
    If this is still an issue with the latest version of Capacitor, please create a new issue and ensure the template is fully filled out.
  dryRun: false