included:
  - ios
  - ios-template
  - plugin-template/ios
opt_in_rules:
  - implicitly_unwrapped_optional
  - file_name_no_space
  - force_unwrapping
  - function_default_parameter_at_end
  - lower_acl_than_parent
  - modifier_order
  - overridden_super_call
  - unowned_variable_capture
  - unused_import
