import { Plugin, PluginType, getPlugins } from '../../plugin';
import { checkCocoaPods, checkIOSProject, getIOSPlugins } from './common';
import { check, isInstalled, log, runCommand, writeFileAsync } from '../../common';
import { join } from 'path';
import { IOS_MIN_VERSION, IOS_PATH, IOS_RUNTIME_POD, LIST_FILE } from '../../config';


export async function updateIOS(needsUpdate: boolean) {
  await check(
    checkCocoaPods,
    checkIOSProject
  );

  const allplugins = await getPlugins();
  const plugins = await getIOSPlugins(allplugins);

  if (plugins.length > 0) {
    log('found', plugins.length, 'native modules\n',
      plugins.map(p => p.id).join('\n'), '\n');
  } else {
    log('no avocado plugin was found, that\'s ok, you can add more plugins later');
  }


  await autoGeneratePods(plugins);
  await installCocoaPodsPlugins(plugins, needsUpdate);

  log('DONE! Native modules are updated 🎉');
}

export async function autoGeneratePods(plugins: Plugin[]): Promise<void[]> {
  return Promise.all(plugins
    .filter(p => p.ios!.type === PluginType.Code)
    .map(async p => {
      const name = p.ios!.name = p.name;
      p.ios!.type = PluginType.Cocoapods;

      const content = generatePodspec(name);
      const path = join(p.ios!.path, name + '.podspec');
      return writeFileAsync(path, content);
    }));
}

export function generatePodspec(name: string) {
  return `
  Pod::Spec.new do |s|
    s.name = '${name}'
    s.version = '0.0.1'
    s.summary = 'Autogenerated spec'
    s.license = 'Unknown'
    s.homepage = 'https://example.com'
    s.authors = { 'Avocado generator' => 'hi@ionicframework.com' }
    s.source = { :git => 'https://github.com/ionic-team/avocado.git', :tag => '0.0.1' }
    s.source_files = '*.{swift,h,m}'
  end`;
}

export async function installCocoaPodsPlugins(plugins: Plugin[], needsUpdate: boolean) {
  const pods = plugins
    .filter(p => p.ios!.type === PluginType.Cocoapods);

  await updatePodfile(pods, needsUpdate);
}

export async function updatePodfile(plugins: Plugin[], needsUpdate: boolean) {
  const content = generatePodFile(plugins);
  const podfilePath = join(IOS_PATH, 'Podfile');
  await writeFileAsync(podfilePath, content, 'utf8');
  if (needsUpdate) {
    log('🐎 cocoapods is resolving native dependencies...');
    await runCommand(`cd ${IOS_PATH} && pod update`);
  } else {
    log('🐎 cocoapods is resolving native dependencies...');
    await runCommand(`cd ${IOS_PATH} && pod install`);
  }
}

export function generatePodFile(plugins: Plugin[]) {
  const pods = plugins
    .map((p) => `pod '${p.ios!.name}', :path => '${p.ios!.path}'`);

  pods.push(IOS_RUNTIME_POD);

  return `
    platform :ios, '${IOS_MIN_VERSION}'
    use_frameworks!

    target 'AvocadoApp' do
      ${pods.join('\n')}
    end`;
}
