#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 5.9 (swiftlang-5.9.0.128.108 clang-1500.0.40.1)
#ifndef CAPACITOR_SWIFT_H
#define CAPACITOR_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import Foundation;
@import ObjectiveC;
@import UIKit;
@import UserNotifications;
@import WebKit;
#endif

#import <Capacitor/Capacitor.h>

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="Capacitor",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)
@class UIApplication;
@class NSURL;
@class NSUserActivity;
@protocol UIUserActivityRestoring;

SWIFT_CLASS_NAMED("ApplicationDelegateProxy")
@interface CAPApplicationDelegateProxy : NSObject <UIApplicationDelegate>
- (BOOL)application:(UIApplication * _Nonnull)app openURL:(NSURL * _Nonnull)url options:(NSDictionary<UIApplicationOpenURLOptionsKey, id> * _Nonnull)options SWIFT_WARN_UNUSED_RESULT;
- (BOOL)application:(UIApplication * _Nonnull)application continueUserActivity:(NSUserActivity * _Nonnull)userActivity restorationHandler:(void (^ _Nonnull)(NSArray<id <UIUserActivityRestoring>> * _Nullable))restorationHandler SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class NSNotification;

SWIFT_CLASS("_TtC9Capacitor9CAPBridge") SWIFT_DEPRECATED_MSG("'statusBarTappedNotification' has been moved to Notification.Name.capacitorStatusBarTapped. 'getLastUrl' and application delegate methods have been moved to ApplicationDelegateProxy.")
@interface CAPBridge : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSNotification * _Nonnull statusBarTappedNotification;)
+ (NSNotification * _Nonnull)statusBarTappedNotification SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class UIViewController;
@class CAPInstanceConfiguration;
@class WKWebView;
@class CAPNotificationRouter;
@class NSString;
@class CAPPluginCall;
@class CAPPlugin;

SWIFT_PROTOCOL("_TtP9Capacitor17CAPBridgeProtocol_")
@protocol CAPBridgeProtocol <NSObject>
@property (nonatomic, readonly, strong) UIViewController * _Nullable viewController;
@property (nonatomic, readonly, strong) CAPInstanceConfiguration * _Nonnull config;
@property (nonatomic, readonly, strong) WKWebView * _Nullable webView;
@property (nonatomic, readonly, strong) CAPNotificationRouter * _Nonnull notificationRouter;
@property (nonatomic, readonly) BOOL isSimEnvironment;
@property (nonatomic, readonly) BOOL isDevEnvironment;
@property (nonatomic, readonly) UIUserInterfaceStyle userInterfaceStyle;
@property (nonatomic, readonly) BOOL autoRegisterPlugins;
@property (nonatomic) BOOL statusBarVisible;
@property (nonatomic) UIStatusBarStyle statusBarStyle;
@property (nonatomic) UIStatusBarAnimation statusBarAnimation;
- (WKWebView * _Nullable)getWebView SWIFT_WARN_UNUSED_RESULT SWIFT_DEPRECATED_MSG("", "webView");
- (BOOL)isSimulator SWIFT_WARN_UNUSED_RESULT SWIFT_DEPRECATED_MSG("", "isSimEnvironment");
- (BOOL)isDevMode SWIFT_WARN_UNUSED_RESULT SWIFT_DEPRECATED_MSG("", "isDevEnvironment");
- (BOOL)getStatusBarVisible SWIFT_WARN_UNUSED_RESULT SWIFT_DEPRECATED_MSG("", "statusBarVisible");
- (UIStatusBarStyle)getStatusBarStyle SWIFT_WARN_UNUSED_RESULT SWIFT_DEPRECATED_MSG("", "statusBarStyle");
- (UIUserInterfaceStyle)getUserInterfaceStyle SWIFT_WARN_UNUSED_RESULT SWIFT_DEPRECATED_MSG("", "userInterfaceStyle");
- (NSString * _Nonnull)getLocalUrl SWIFT_WARN_UNUSED_RESULT SWIFT_DEPRECATED_MSG("Moved - equivalent is found on config.localURL");
- (CAPPluginCall * _Nullable)getSavedCall:(NSString * _Nonnull)callbackId SWIFT_WARN_UNUSED_RESULT SWIFT_DEPRECATED_MSG("", "savedCallWithID:");
- (void)releaseCallWithCallbackId:(NSString * _Nonnull)callbackId SWIFT_DEPRECATED_MSG("", "releaseCallWithID:");
- (CAPPlugin * _Nullable)pluginWithName:(NSString * _Nonnull)withName SWIFT_WARN_UNUSED_RESULT;
- (void)saveCall:(CAPPluginCall * _Nonnull)call;
- (CAPPluginCall * _Nullable)savedCallWithID:(NSString * _Nonnull)withID SWIFT_WARN_UNUSED_RESULT;
- (void)releaseCall:(CAPPluginCall * _Nonnull)call;
- (void)releaseCallWithID:(NSString * _Nonnull)withID;
- (void)evalWithPlugin:(CAPPlugin * _Nonnull)plugin js:(NSString * _Nonnull)js;
- (void)evalWithJs:(NSString * _Nonnull)js;
- (void)triggerJSEventWithEventName:(NSString * _Nonnull)eventName target:(NSString * _Nonnull)target;
- (void)triggerJSEventWithEventName:(NSString * _Nonnull)eventName target:(NSString * _Nonnull)target data:(NSString * _Nonnull)data;
- (void)triggerWindowJSEventWithEventName:(NSString * _Nonnull)eventName;
- (void)triggerWindowJSEventWithEventName:(NSString * _Nonnull)eventName data:(NSString * _Nonnull)data;
- (void)triggerDocumentJSEventWithEventName:(NSString * _Nonnull)eventName;
- (void)triggerDocumentJSEventWithEventName:(NSString * _Nonnull)eventName data:(NSString * _Nonnull)data;
- (NSURL * _Nullable)localURLFromWebURL:(NSURL * _Nullable)webURL SWIFT_WARN_UNUSED_RESULT;
- (NSURL * _Nullable)portablePathFromLocalURL:(NSURL * _Nullable)localURL SWIFT_WARN_UNUSED_RESULT;
- (void)setServerBasePath:(NSString * _Nonnull)path;
- (void)registerPluginType:(SWIFT_METATYPE(CAPPlugin) _Nonnull)pluginType;
- (void)registerPluginInstance:(CAPPlugin * _Nonnull)pluginInstance;
- (void)showAlertWithTitle:(NSString * _Nonnull)title message:(NSString * _Nonnull)message buttonTitle:(NSString * _Nonnull)buttonTitle;
- (void)presentVC:(UIViewController * _Nonnull)viewControllerToPresent animated:(BOOL)flag completion:(void (^ _Nullable)(void))completion;
- (void)dismissVCWithAnimated:(BOOL)flag completion:(void (^ _Nullable)(void))completion;
@end

@class NSBundle;
@class NSCoder;

SWIFT_CLASS("_TtC9Capacitor23CAPBridgeViewController")
@interface CAPBridgeViewController : UIViewController
@property (nonatomic, copy) NSArray<NSNumber *> * _Nonnull supportedOrientations;
- (void)loadView;
- (void)viewDidLoad;
- (BOOL)canPerformUnwindSegueAction:(SEL _Nonnull)action fromViewController:(UIViewController * _Nonnull)fromViewController withSender:(id _Nonnull)sender SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, readonly) BOOL prefersStatusBarHidden;
@property (nonatomic, readonly) UIStatusBarStyle preferredStatusBarStyle;
@property (nonatomic, readonly) UIStatusBarAnimation preferredStatusBarUpdateAnimation;
@property (nonatomic, readonly) UIInterfaceOrientationMask supportedInterfaceOrientations;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


@interface CAPBridgeViewController (SWIFT_EXTENSION(Capacitor))
- (NSString * _Nonnull)getServerBasePath SWIFT_WARN_UNUSED_RESULT;
- (void)setServerBasePathWithPath:(NSString * _Nonnull)path;
@end




SWIFT_CLASS_NAMED("CAPConsolePlugin")
@interface CAPConsolePlugin : CAPPlugin
- (void)log:(CAPPluginCall * _Nonnull)call;
- (nonnull instancetype)initWithBridge:(id <CAPBridgeProtocol> _Nonnull)bridge pluginId:(NSString * _Nonnull)pluginId pluginName:(NSString * _Nonnull)pluginName OBJC_DESIGNATED_INITIALIZER SWIFT_DEPRECATED_MSG("This initializer is deprecated and is not suggested for use. Any data set through this init method will be overridden when it is loaded on the bridge.");
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("CAPCookiesPlugin")
@interface CAPCookiesPlugin : CAPPlugin
- (void)load;
- (nonnull instancetype)initWithBridge:(id <CAPBridgeProtocol> _Nonnull)bridge pluginId:(NSString * _Nonnull)pluginId pluginName:(NSString * _Nonnull)pluginName OBJC_DESIGNATED_INITIALIZER SWIFT_DEPRECATED_MSG("This initializer is deprecated and is not suggested for use. Any data set through this init method will be overridden when it is loaded on the bridge.");
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


/// CAPFileManager helps map file schemes to physical files, whether they are on
/// disk, in a bundle, or in another location.
SWIFT_CLASS("_TtC9Capacitor14CAPFileManager")
@interface CAPFileManager : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("CAPHttpPlugin")
@interface CAPHttpPlugin : CAPPlugin
- (nonnull instancetype)initWithBridge:(id <CAPBridgeProtocol> _Nonnull)bridge pluginId:(NSString * _Nonnull)pluginId pluginName:(NSString * _Nonnull)pluginName OBJC_DESIGNATED_INITIALIZER SWIFT_DEPRECATED_MSG("This initializer is deprecated and is not suggested for use. Any data set through this init method will be overridden when it is loaded on the bridge.");
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


/// A CAPPlugin subclass meant to be explicitly initialized by the caller and not the bridge.
SWIFT_CLASS("_TtC9Capacitor17CAPInstancePlugin")
@interface CAPInstancePlugin : CAPPlugin
- (nonnull instancetype)initWithBridge:(id <CAPBridgeProtocol> _Nonnull)bridge pluginId:(NSString * _Nonnull)pluginId pluginName:(NSString * _Nonnull)pluginName OBJC_DESIGNATED_INITIALIZER SWIFT_DEPRECATED_MSG("This initializer is deprecated and is not suggested for use. Any data set through this init method will be overridden when it is loaded on the bridge.");
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

/// Deprecated, will be removed
typedef SWIFT_ENUM(NSInteger, CAPNotifications, open) {
  CAPNotificationsURLOpen = 0,
  CAPNotificationsUniversalLinkOpen = 1,
  CAPNotificationsContinueActivity = 2,
  CAPNotificationsDidRegisterForRemoteNotificationsWithDeviceToken = 3,
  CAPNotificationsDidFailToRegisterForRemoteNotificationsWithError = 4,
  CAPNotificationsDecidePolicyForNavigationAction = 5,
};


@class NSISO8601DateFormatter;

@interface CAPPluginCall (SWIFT_EXTENSION(Capacitor))
@property (nonatomic, readonly, strong) NSDictionary * _Nonnull dictionaryRepresentation;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, strong) NSISO8601DateFormatter * _Nonnull jsDateFormatter;)
+ (NSISO8601DateFormatter * _Nonnull)jsDateFormatter SWIFT_WARN_UNUSED_RESULT;
+ (void)setJsDateFormatter:(NSISO8601DateFormatter * _Nonnull)value;
@end


@interface CAPPluginCall (SWIFT_EXTENSION(Capacitor))
- (BOOL)hasOption:(NSString * _Nonnull)key SWIFT_WARN_UNUSED_RESULT SWIFT_DEPRECATED_MSG("Presence of a key should not be considered significant. Use typed accessors to check the value instead.");
- (void)success SWIFT_DEPRECATED_MSG("", "resolve");
- (void)success:(NSDictionary<NSString *, id> * _Nonnull)data SWIFT_DEPRECATED_MSG("", "resolve:");
- (void)resolve;
- (void)resolve:(NSDictionary<NSString *, id> * _Nonnull)data;
- (void)error:(NSString * _Nonnull)message :(NSError * _Nullable)error :(NSDictionary<NSString *, id> * _Nonnull)data SWIFT_DEPRECATED_MSG("", "reject::::");
- (void)reject:(NSString * _Nonnull)message :(NSString * _Nullable)code :(NSError * _Nullable)error :(NSDictionary<NSString *, id> * _Nullable)data;
- (void)unimplemented;
- (void)unimplemented:(NSString * _Nonnull)message;
- (void)unavailable;
- (void)unavailable:(NSString * _Nonnull)message;
@end


SWIFT_CLASS("_TtC9Capacitor18CAPPluginCallError")
@interface CAPPluginCallError : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull message;
@property (nonatomic, readonly, copy) NSString * _Nullable code;
@property (nonatomic, readonly) NSError * _Nullable error;
@property (nonatomic, readonly, copy) NSDictionary<NSString *, id> * _Nullable data;
- (nonnull instancetype)init:(NSString * _Nonnull)message code:(NSString * _Nullable)code error:(NSError * _Nullable)error data:(NSDictionary<NSString *, id> * _Nullable)data OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC9Capacitor19CAPPluginCallResult")
@interface CAPPluginCallResult : NSObject
@property (nonatomic, readonly, copy) NSDictionary<NSString *, id> * _Nullable data;
- (nonnull instancetype)init:(NSDictionary<NSString *, id> * _Nullable)data OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("CAPWebViewPlugin")
@interface CAPWebViewPlugin : CAPPlugin
- (nonnull instancetype)initWithBridge:(id <CAPBridgeProtocol> _Nonnull)bridge pluginId:(NSString * _Nonnull)pluginId pluginName:(NSString * _Nonnull)pluginName OBJC_DESIGNATED_INITIALIZER SWIFT_DEPRECATED_MSG("This initializer is deprecated and is not suggested for use. Any data set through this init method will be overridden when it is loaded on the bridge.");
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC9Capacitor15CapacitorBridge")
@interface CapacitorBridge : NSObject <CAPBridgeProtocol>
@property (nonatomic, readonly, strong) WKWebView * _Nullable webView;
@property (nonatomic, readonly) BOOL autoRegisterPlugins;
@property (nonatomic, strong) CAPNotificationRouter * _Nonnull notificationRouter;
@property (nonatomic, readonly) BOOL isSimEnvironment;
@property (nonatomic, readonly) BOOL isDevEnvironment;
@property (nonatomic, readonly) UIUserInterfaceStyle userInterfaceStyle;
@property (nonatomic) BOOL statusBarVisible;
@property (nonatomic) UIStatusBarStyle statusBarStyle;
@property (nonatomic) UIStatusBarAnimation statusBarAnimation;
@property (nonatomic, readonly, strong) UIViewController * _Nullable viewController;
@property (nonatomic, strong) CAPInstanceConfiguration * _Nonnull config;
- (WKWebView * _Nullable)getWebView SWIFT_WARN_UNUSED_RESULT;
- (BOOL)isSimulator SWIFT_WARN_UNUSED_RESULT;
- (BOOL)isDevMode SWIFT_WARN_UNUSED_RESULT;
- (BOOL)getStatusBarVisible SWIFT_WARN_UNUSED_RESULT;
- (UIStatusBarStyle)getStatusBarStyle SWIFT_WARN_UNUSED_RESULT;
- (UIUserInterfaceStyle)getUserInterfaceStyle SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getLocalUrl SWIFT_WARN_UNUSED_RESULT;
- (void)setServerBasePath:(NSString * _Nonnull)path;
- (void)registerPluginType:(SWIFT_METATYPE(CAPPlugin) _Nonnull)pluginType;
- (void)registerPluginInstance:(CAPPlugin * _Nonnull)pluginInstance;
- (CAPPlugin * _Nullable)pluginWithName:(NSString * _Nonnull)withName SWIFT_WARN_UNUSED_RESULT;
- (void)saveCall:(CAPPluginCall * _Nonnull)call;
- (CAPPluginCall * _Nullable)savedCallWithID:(NSString * _Nonnull)withID SWIFT_WARN_UNUSED_RESULT;
- (void)releaseCall:(CAPPluginCall * _Nonnull)call;
- (void)releaseCallWithID:(NSString * _Nonnull)withID;
- (CAPPluginCall * _Nullable)getSavedCall:(NSString * _Nonnull)callbackId SWIFT_WARN_UNUSED_RESULT;
- (void)releaseCallWithCallbackId:(NSString * _Nonnull)callbackId;
- (void)evalWithPlugin:(CAPPlugin * _Nonnull)plugin js:(NSString * _Nonnull)js;
- (void)evalWithJs:(NSString * _Nonnull)js;
- (void)triggerJSEventWithEventName:(NSString * _Nonnull)eventName target:(NSString * _Nonnull)target;
- (void)triggerJSEventWithEventName:(NSString * _Nonnull)eventName target:(NSString * _Nonnull)target data:(NSString * _Nonnull)data;
- (void)triggerWindowJSEventWithEventName:(NSString * _Nonnull)eventName;
- (void)triggerWindowJSEventWithEventName:(NSString * _Nonnull)eventName data:(NSString * _Nonnull)data;
- (void)triggerDocumentJSEventWithEventName:(NSString * _Nonnull)eventName;
- (void)triggerDocumentJSEventWithEventName:(NSString * _Nonnull)eventName data:(NSString * _Nonnull)data;
/// Translate a URL from the web view into a file URL for native iOS.
/// The web view may be handling several different types of URLs:
/// <ul>
///   <li>
///     res:// (shortcut scheme to web assets)
///   </li>
///   <li>
///     file:// (fully qualified URL to file on the local device)
///   </li>
///   <li>
///     base64:// (to be implemented)
///   </li>
///   <li>
///   </li>
/// </ul>
- (NSURL * _Nullable)localURLFromWebURL:(NSURL * _Nullable)webURL SWIFT_WARN_UNUSED_RESULT;
/// Translate a file URL for native iOS into a URL to load in the web view.
- (NSURL * _Nullable)portablePathFromLocalURL:(NSURL * _Nullable)localURL SWIFT_WARN_UNUSED_RESULT;
- (void)showAlertWithTitle:(NSString * _Nonnull)title message:(NSString * _Nonnull)message buttonTitle:(NSString * _Nonnull)buttonTitle;
- (void)presentVC:(UIViewController * _Nonnull)viewControllerToPresent animated:(BOOL)flag completion:(void (^ _Nullable)(void))completion;
- (void)dismissVCWithAnimated:(BOOL)flag completion:(void (^ _Nullable)(void))completion;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class NSURLSession;
@class NSURLSessionTask;
@class NSHTTPURLResponse;
@class NSURLRequest;

SWIFT_CLASS("_TtC9Capacitor19CapacitorUrlRequest")
@interface CapacitorUrlRequest : NSObject <NSURLSessionTaskDelegate>
- (void)URLSession:(NSURLSession * _Nonnull)session task:(NSURLSessionTask * _Nonnull)task willPerformHTTPRedirection:(NSHTTPURLResponse * _Nonnull)response newRequest:(NSURLRequest * _Nonnull)request completionHandler:(void (^ _Nonnull)(NSURLRequest * _Nullable))completionHandler;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class WKHTTPCookieStore;

SWIFT_CLASS("_TtC9Capacitor25CapacitorWKCookieObserver")
@interface CapacitorWKCookieObserver : NSObject <WKHTTPCookieStoreObserver>
- (void)cookiesDidChangeInCookieStore:(WKHTTPCookieStore * _Nonnull)cookieStore;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class PluginConfig;

@interface CAPInstanceConfiguration (SWIFT_EXTENSION(Capacitor))
@property (nonatomic, readonly, copy) NSURL * _Nonnull appStartFileURL;
@property (nonatomic, readonly, copy) NSURL * _Nonnull appStartServerURL;
@property (nonatomic, readonly, copy) NSURL * _Nullable errorPathURL;
- (id _Nullable)getPluginConfigValue:(NSString * _Nonnull)pluginId :(NSString * _Nonnull)configKey SWIFT_WARN_UNUSED_RESULT SWIFT_DEPRECATED_MSG("Use getPluginConfig");
- (PluginConfig * _Nonnull)getPluginConfig:(NSString * _Nonnull)pluginId SWIFT_WARN_UNUSED_RESULT;
- (BOOL)shouldAllowNavigationTo:(NSString * _Nonnull)host SWIFT_WARN_UNUSED_RESULT;
- (id _Nullable)getValue:(NSString * _Nonnull)key SWIFT_WARN_UNUSED_RESULT SWIFT_DEPRECATED_MSG("Use direct property accessors");
- (NSString * _Nullable)getString:(NSString * _Nonnull)key SWIFT_WARN_UNUSED_RESULT SWIFT_DEPRECATED_MSG("Use direct property accessors");
@end



@interface CAPInstanceDescriptor (SWIFT_EXTENSION(Capacitor))
@property (nonatomic, readonly) BOOL cordovaDeployDisabled;
- (void)normalize;
@end


@interface NSNotification (SWIFT_EXTENSION(Capacitor))
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSNotificationName _Nonnull capacitorOpenURL;)
+ (NSNotificationName _Nonnull)capacitorOpenURL SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSNotificationName _Nonnull capacitorOpenUniversalLink;)
+ (NSNotificationName _Nonnull)capacitorOpenUniversalLink SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSNotificationName _Nonnull capacitorContinueActivity;)
+ (NSNotificationName _Nonnull)capacitorContinueActivity SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSNotificationName _Nonnull capacitorDidRegisterForRemoteNotifications;)
+ (NSNotificationName _Nonnull)capacitorDidRegisterForRemoteNotifications SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSNotificationName _Nonnull capacitorDidFailToRegisterForRemoteNotifications;)
+ (NSNotificationName _Nonnull)capacitorDidFailToRegisterForRemoteNotifications SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSNotificationName _Nonnull capacitorDecidePolicyForNavigationAction;)
+ (NSNotificationName _Nonnull)capacitorDecidePolicyForNavigationAction SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSNotificationName _Nonnull capacitorStatusBarTapped;)
+ (NSNotificationName _Nonnull)capacitorStatusBarTapped SWIFT_WARN_UNUSED_RESULT;
@end



@class UNNotification;
@class UNNotificationResponse;

SWIFT_PROTOCOL_NAMED("NotificationHandlerProtocol")
@protocol CAPNotificationHandlerProtocol
- (UNNotificationPresentationOptions)willPresentWithNotification:(UNNotification * _Nonnull)notification SWIFT_WARN_UNUSED_RESULT;
- (void)didReceiveWithResponse:(UNNotificationResponse * _Nonnull)response;
@end

@class UNUserNotificationCenter;

SWIFT_CLASS_NAMED("NotificationRouter")
@interface CAPNotificationRouter : NSObject <UNUserNotificationCenterDelegate>
- (void)userNotificationCenter:(UNUserNotificationCenter * _Nonnull)center willPresentNotification:(UNNotification * _Nonnull)notification withCompletionHandler:(void (^ _Nonnull)(UNNotificationPresentationOptions))completionHandler;
- (void)userNotificationCenter:(UNUserNotificationCenter * _Nonnull)center didReceiveNotificationResponse:(UNNotificationResponse * _Nonnull)response withCompletionHandler:(void (^ _Nonnull)(void))completionHandler;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC9Capacitor12PluginConfig")
@interface PluginConfig : NSObject
- (NSString * _Nullable)getString:(NSString * _Nonnull)configKey :(NSString * _Nullable)defaultValue SWIFT_WARN_UNUSED_RESULT;
- (BOOL)getBoolean:(NSString * _Nonnull)configKey :(BOOL)defaultValue SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)getInt:(NSString * _Nonnull)configKey :(NSInteger)defaultValue SWIFT_WARN_UNUSED_RESULT;
- (BOOL)isEmpty SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end




@protocol WKURLSchemeTask;

SWIFT_CLASS_NAMED("WebViewAssetHandler")
@interface CAPWebViewAssetHandler : NSObject <WKURLSchemeHandler>
- (void)webView:(WKWebView * _Nonnull)webView startURLSchemeTask:(id <WKURLSchemeTask> _Nonnull)urlSchemeTask;
- (void)webView:(WKWebView * _Nonnull)webView stopURLSchemeTask:(id <WKURLSchemeTask> _Nonnull)urlSchemeTask;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class WKNavigation;
@class WKSecurityOrigin;
@class WKFrameInfo;
@class WKNavigationAction;
@class WKUserContentController;
@class WKScriptMessage;
@class WKWebViewConfiguration;
@class WKWindowFeatures;
@class UIScrollView;
@class UIView;

SWIFT_CLASS_NAMED("WebViewDelegationHandler")
@interface CAPWebViewDelegationHandler : NSObject <UIScrollViewDelegate, WKNavigationDelegate, WKScriptMessageHandler, WKUIDelegate>
- (void)webView:(WKWebView * _Nonnull)webView didStartProvisionalNavigation:(WKNavigation * _Null_unspecified)navigation;
- (void)webView:(WKWebView * _Nonnull)webView requestMediaCapturePermissionForOrigin:(WKSecurityOrigin * _Nonnull)origin initiatedByFrame:(WKFrameInfo * _Nonnull)frame type:(WKMediaCaptureType)type decisionHandler:(void (^ _Nonnull)(WKPermissionDecision))decisionHandler SWIFT_AVAILABILITY(ios,introduced=15);
- (void)webView:(WKWebView * _Nonnull)webView requestDeviceOrientationAndMotionPermissionForOrigin:(WKSecurityOrigin * _Nonnull)origin initiatedByFrame:(WKFrameInfo * _Nonnull)frame decisionHandler:(void (^ _Nonnull)(WKPermissionDecision))decisionHandler SWIFT_AVAILABILITY(ios,introduced=15);
- (void)webView:(WKWebView * _Nonnull)webView decidePolicyForNavigationAction:(WKNavigationAction * _Nonnull)navigationAction decisionHandler:(void (^ _Nonnull)(WKNavigationActionPolicy))decisionHandler;
- (void)webView:(WKWebView * _Nonnull)webView didFinishNavigation:(WKNavigation * _Null_unspecified)navigation;
- (void)webView:(WKWebView * _Nonnull)webView didFailNavigation:(WKNavigation * _Null_unspecified)navigation withError:(NSError * _Nonnull)error;
- (void)webView:(WKWebView * _Nonnull)webView didFailProvisionalNavigation:(WKNavigation * _Null_unspecified)navigation withError:(NSError * _Nonnull)error;
- (void)webViewWebContentProcessDidTerminate:(WKWebView * _Nonnull)webView;
- (void)userContentController:(WKUserContentController * _Nonnull)userContentController didReceiveScriptMessage:(WKScriptMessage * _Nonnull)message;
- (void)webView:(WKWebView * _Nonnull)webView runJavaScriptAlertPanelWithMessage:(NSString * _Nonnull)message initiatedByFrame:(WKFrameInfo * _Nonnull)frame completionHandler:(void (^ _Nonnull)(void))completionHandler;
- (void)webView:(WKWebView * _Nonnull)webView runJavaScriptConfirmPanelWithMessage:(NSString * _Nonnull)message initiatedByFrame:(WKFrameInfo * _Nonnull)frame completionHandler:(void (^ _Nonnull)(BOOL))completionHandler;
- (void)webView:(WKWebView * _Nonnull)webView runJavaScriptTextInputPanelWithPrompt:(NSString * _Nonnull)prompt defaultText:(NSString * _Nullable)defaultText initiatedByFrame:(WKFrameInfo * _Nonnull)frame completionHandler:(void (^ _Nonnull)(NSString * _Nullable))completionHandler;
- (WKWebView * _Nullable)webView:(WKWebView * _Nonnull)webView createWebViewWithConfiguration:(WKWebViewConfiguration * _Nonnull)configuration forNavigationAction:(WKNavigationAction * _Nonnull)navigationAction windowFeatures:(WKWindowFeatures * _Nonnull)windowFeatures SWIFT_WARN_UNUSED_RESULT;
- (void)scrollViewWillBeginZooming:(UIScrollView * _Nonnull)scrollView withView:(UIView * _Nullable)view;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#elif defined(__x86_64__) && __x86_64__
// Generated by Apple Swift version 5.9 (swiftlang-5.9.0.128.108 clang-1500.0.40.1)
#ifndef CAPACITOR_SWIFT_H
#define CAPACITOR_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import Foundation;
@import ObjectiveC;
@import UIKit;
@import UserNotifications;
@import WebKit;
#endif

#import <Capacitor/Capacitor.h>

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="Capacitor",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)
@class UIApplication;
@class NSURL;
@class NSUserActivity;
@protocol UIUserActivityRestoring;

SWIFT_CLASS_NAMED("ApplicationDelegateProxy")
@interface CAPApplicationDelegateProxy : NSObject <UIApplicationDelegate>
- (BOOL)application:(UIApplication * _Nonnull)app openURL:(NSURL * _Nonnull)url options:(NSDictionary<UIApplicationOpenURLOptionsKey, id> * _Nonnull)options SWIFT_WARN_UNUSED_RESULT;
- (BOOL)application:(UIApplication * _Nonnull)application continueUserActivity:(NSUserActivity * _Nonnull)userActivity restorationHandler:(void (^ _Nonnull)(NSArray<id <UIUserActivityRestoring>> * _Nullable))restorationHandler SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class NSNotification;

SWIFT_CLASS("_TtC9Capacitor9CAPBridge") SWIFT_DEPRECATED_MSG("'statusBarTappedNotification' has been moved to Notification.Name.capacitorStatusBarTapped. 'getLastUrl' and application delegate methods have been moved to ApplicationDelegateProxy.")
@interface CAPBridge : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSNotification * _Nonnull statusBarTappedNotification;)
+ (NSNotification * _Nonnull)statusBarTappedNotification SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class UIViewController;
@class CAPInstanceConfiguration;
@class WKWebView;
@class CAPNotificationRouter;
@class NSString;
@class CAPPluginCall;
@class CAPPlugin;

SWIFT_PROTOCOL("_TtP9Capacitor17CAPBridgeProtocol_")
@protocol CAPBridgeProtocol <NSObject>
@property (nonatomic, readonly, strong) UIViewController * _Nullable viewController;
@property (nonatomic, readonly, strong) CAPInstanceConfiguration * _Nonnull config;
@property (nonatomic, readonly, strong) WKWebView * _Nullable webView;
@property (nonatomic, readonly, strong) CAPNotificationRouter * _Nonnull notificationRouter;
@property (nonatomic, readonly) BOOL isSimEnvironment;
@property (nonatomic, readonly) BOOL isDevEnvironment;
@property (nonatomic, readonly) UIUserInterfaceStyle userInterfaceStyle;
@property (nonatomic, readonly) BOOL autoRegisterPlugins;
@property (nonatomic) BOOL statusBarVisible;
@property (nonatomic) UIStatusBarStyle statusBarStyle;
@property (nonatomic) UIStatusBarAnimation statusBarAnimation;
- (WKWebView * _Nullable)getWebView SWIFT_WARN_UNUSED_RESULT SWIFT_DEPRECATED_MSG("", "webView");
- (BOOL)isSimulator SWIFT_WARN_UNUSED_RESULT SWIFT_DEPRECATED_MSG("", "isSimEnvironment");
- (BOOL)isDevMode SWIFT_WARN_UNUSED_RESULT SWIFT_DEPRECATED_MSG("", "isDevEnvironment");
- (BOOL)getStatusBarVisible SWIFT_WARN_UNUSED_RESULT SWIFT_DEPRECATED_MSG("", "statusBarVisible");
- (UIStatusBarStyle)getStatusBarStyle SWIFT_WARN_UNUSED_RESULT SWIFT_DEPRECATED_MSG("", "statusBarStyle");
- (UIUserInterfaceStyle)getUserInterfaceStyle SWIFT_WARN_UNUSED_RESULT SWIFT_DEPRECATED_MSG("", "userInterfaceStyle");
- (NSString * _Nonnull)getLocalUrl SWIFT_WARN_UNUSED_RESULT SWIFT_DEPRECATED_MSG("Moved - equivalent is found on config.localURL");
- (CAPPluginCall * _Nullable)getSavedCall:(NSString * _Nonnull)callbackId SWIFT_WARN_UNUSED_RESULT SWIFT_DEPRECATED_MSG("", "savedCallWithID:");
- (void)releaseCallWithCallbackId:(NSString * _Nonnull)callbackId SWIFT_DEPRECATED_MSG("", "releaseCallWithID:");
- (CAPPlugin * _Nullable)pluginWithName:(NSString * _Nonnull)withName SWIFT_WARN_UNUSED_RESULT;
- (void)saveCall:(CAPPluginCall * _Nonnull)call;
- (CAPPluginCall * _Nullable)savedCallWithID:(NSString * _Nonnull)withID SWIFT_WARN_UNUSED_RESULT;
- (void)releaseCall:(CAPPluginCall * _Nonnull)call;
- (void)releaseCallWithID:(NSString * _Nonnull)withID;
- (void)evalWithPlugin:(CAPPlugin * _Nonnull)plugin js:(NSString * _Nonnull)js;
- (void)evalWithJs:(NSString * _Nonnull)js;
- (void)triggerJSEventWithEventName:(NSString * _Nonnull)eventName target:(NSString * _Nonnull)target;
- (void)triggerJSEventWithEventName:(NSString * _Nonnull)eventName target:(NSString * _Nonnull)target data:(NSString * _Nonnull)data;
- (void)triggerWindowJSEventWithEventName:(NSString * _Nonnull)eventName;
- (void)triggerWindowJSEventWithEventName:(NSString * _Nonnull)eventName data:(NSString * _Nonnull)data;
- (void)triggerDocumentJSEventWithEventName:(NSString * _Nonnull)eventName;
- (void)triggerDocumentJSEventWithEventName:(NSString * _Nonnull)eventName data:(NSString * _Nonnull)data;
- (NSURL * _Nullable)localURLFromWebURL:(NSURL * _Nullable)webURL SWIFT_WARN_UNUSED_RESULT;
- (NSURL * _Nullable)portablePathFromLocalURL:(NSURL * _Nullable)localURL SWIFT_WARN_UNUSED_RESULT;
- (void)setServerBasePath:(NSString * _Nonnull)path;
- (void)registerPluginType:(SWIFT_METATYPE(CAPPlugin) _Nonnull)pluginType;
- (void)registerPluginInstance:(CAPPlugin * _Nonnull)pluginInstance;
- (void)showAlertWithTitle:(NSString * _Nonnull)title message:(NSString * _Nonnull)message buttonTitle:(NSString * _Nonnull)buttonTitle;
- (void)presentVC:(UIViewController * _Nonnull)viewControllerToPresent animated:(BOOL)flag completion:(void (^ _Nullable)(void))completion;
- (void)dismissVCWithAnimated:(BOOL)flag completion:(void (^ _Nullable)(void))completion;
@end

@class NSBundle;
@class NSCoder;

SWIFT_CLASS("_TtC9Capacitor23CAPBridgeViewController")
@interface CAPBridgeViewController : UIViewController
@property (nonatomic, copy) NSArray<NSNumber *> * _Nonnull supportedOrientations;
- (void)loadView;
- (void)viewDidLoad;
- (BOOL)canPerformUnwindSegueAction:(SEL _Nonnull)action fromViewController:(UIViewController * _Nonnull)fromViewController withSender:(id _Nonnull)sender SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, readonly) BOOL prefersStatusBarHidden;
@property (nonatomic, readonly) UIStatusBarStyle preferredStatusBarStyle;
@property (nonatomic, readonly) UIStatusBarAnimation preferredStatusBarUpdateAnimation;
@property (nonatomic, readonly) UIInterfaceOrientationMask supportedInterfaceOrientations;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


@interface CAPBridgeViewController (SWIFT_EXTENSION(Capacitor))
- (NSString * _Nonnull)getServerBasePath SWIFT_WARN_UNUSED_RESULT;
- (void)setServerBasePathWithPath:(NSString * _Nonnull)path;
@end




SWIFT_CLASS_NAMED("CAPConsolePlugin")
@interface CAPConsolePlugin : CAPPlugin
- (void)log:(CAPPluginCall * _Nonnull)call;
- (nonnull instancetype)initWithBridge:(id <CAPBridgeProtocol> _Nonnull)bridge pluginId:(NSString * _Nonnull)pluginId pluginName:(NSString * _Nonnull)pluginName OBJC_DESIGNATED_INITIALIZER SWIFT_DEPRECATED_MSG("This initializer is deprecated and is not suggested for use. Any data set through this init method will be overridden when it is loaded on the bridge.");
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("CAPCookiesPlugin")
@interface CAPCookiesPlugin : CAPPlugin
- (void)load;
- (nonnull instancetype)initWithBridge:(id <CAPBridgeProtocol> _Nonnull)bridge pluginId:(NSString * _Nonnull)pluginId pluginName:(NSString * _Nonnull)pluginName OBJC_DESIGNATED_INITIALIZER SWIFT_DEPRECATED_MSG("This initializer is deprecated and is not suggested for use. Any data set through this init method will be overridden when it is loaded on the bridge.");
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


/// CAPFileManager helps map file schemes to physical files, whether they are on
/// disk, in a bundle, or in another location.
SWIFT_CLASS("_TtC9Capacitor14CAPFileManager")
@interface CAPFileManager : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("CAPHttpPlugin")
@interface CAPHttpPlugin : CAPPlugin
- (nonnull instancetype)initWithBridge:(id <CAPBridgeProtocol> _Nonnull)bridge pluginId:(NSString * _Nonnull)pluginId pluginName:(NSString * _Nonnull)pluginName OBJC_DESIGNATED_INITIALIZER SWIFT_DEPRECATED_MSG("This initializer is deprecated and is not suggested for use. Any data set through this init method will be overridden when it is loaded on the bridge.");
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


/// A CAPPlugin subclass meant to be explicitly initialized by the caller and not the bridge.
SWIFT_CLASS("_TtC9Capacitor17CAPInstancePlugin")
@interface CAPInstancePlugin : CAPPlugin
- (nonnull instancetype)initWithBridge:(id <CAPBridgeProtocol> _Nonnull)bridge pluginId:(NSString * _Nonnull)pluginId pluginName:(NSString * _Nonnull)pluginName OBJC_DESIGNATED_INITIALIZER SWIFT_DEPRECATED_MSG("This initializer is deprecated and is not suggested for use. Any data set through this init method will be overridden when it is loaded on the bridge.");
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

/// Deprecated, will be removed
typedef SWIFT_ENUM(NSInteger, CAPNotifications, open) {
  CAPNotificationsURLOpen = 0,
  CAPNotificationsUniversalLinkOpen = 1,
  CAPNotificationsContinueActivity = 2,
  CAPNotificationsDidRegisterForRemoteNotificationsWithDeviceToken = 3,
  CAPNotificationsDidFailToRegisterForRemoteNotificationsWithError = 4,
  CAPNotificationsDecidePolicyForNavigationAction = 5,
};


@class NSISO8601DateFormatter;

@interface CAPPluginCall (SWIFT_EXTENSION(Capacitor))
@property (nonatomic, readonly, strong) NSDictionary * _Nonnull dictionaryRepresentation;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, strong) NSISO8601DateFormatter * _Nonnull jsDateFormatter;)
+ (NSISO8601DateFormatter * _Nonnull)jsDateFormatter SWIFT_WARN_UNUSED_RESULT;
+ (void)setJsDateFormatter:(NSISO8601DateFormatter * _Nonnull)value;
@end


@interface CAPPluginCall (SWIFT_EXTENSION(Capacitor))
- (BOOL)hasOption:(NSString * _Nonnull)key SWIFT_WARN_UNUSED_RESULT SWIFT_DEPRECATED_MSG("Presence of a key should not be considered significant. Use typed accessors to check the value instead.");
- (void)success SWIFT_DEPRECATED_MSG("", "resolve");
- (void)success:(NSDictionary<NSString *, id> * _Nonnull)data SWIFT_DEPRECATED_MSG("", "resolve:");
- (void)resolve;
- (void)resolve:(NSDictionary<NSString *, id> * _Nonnull)data;
- (void)error:(NSString * _Nonnull)message :(NSError * _Nullable)error :(NSDictionary<NSString *, id> * _Nonnull)data SWIFT_DEPRECATED_MSG("", "reject::::");
- (void)reject:(NSString * _Nonnull)message :(NSString * _Nullable)code :(NSError * _Nullable)error :(NSDictionary<NSString *, id> * _Nullable)data;
- (void)unimplemented;
- (void)unimplemented:(NSString * _Nonnull)message;
- (void)unavailable;
- (void)unavailable:(NSString * _Nonnull)message;
@end


SWIFT_CLASS("_TtC9Capacitor18CAPPluginCallError")
@interface CAPPluginCallError : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull message;
@property (nonatomic, readonly, copy) NSString * _Nullable code;
@property (nonatomic, readonly) NSError * _Nullable error;
@property (nonatomic, readonly, copy) NSDictionary<NSString *, id> * _Nullable data;
- (nonnull instancetype)init:(NSString * _Nonnull)message code:(NSString * _Nullable)code error:(NSError * _Nullable)error data:(NSDictionary<NSString *, id> * _Nullable)data OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC9Capacitor19CAPPluginCallResult")
@interface CAPPluginCallResult : NSObject
@property (nonatomic, readonly, copy) NSDictionary<NSString *, id> * _Nullable data;
- (nonnull instancetype)init:(NSDictionary<NSString *, id> * _Nullable)data OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("CAPWebViewPlugin")
@interface CAPWebViewPlugin : CAPPlugin
- (nonnull instancetype)initWithBridge:(id <CAPBridgeProtocol> _Nonnull)bridge pluginId:(NSString * _Nonnull)pluginId pluginName:(NSString * _Nonnull)pluginName OBJC_DESIGNATED_INITIALIZER SWIFT_DEPRECATED_MSG("This initializer is deprecated and is not suggested for use. Any data set through this init method will be overridden when it is loaded on the bridge.");
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC9Capacitor15CapacitorBridge")
@interface CapacitorBridge : NSObject <CAPBridgeProtocol>
@property (nonatomic, readonly, strong) WKWebView * _Nullable webView;
@property (nonatomic, readonly) BOOL autoRegisterPlugins;
@property (nonatomic, strong) CAPNotificationRouter * _Nonnull notificationRouter;
@property (nonatomic, readonly) BOOL isSimEnvironment;
@property (nonatomic, readonly) BOOL isDevEnvironment;
@property (nonatomic, readonly) UIUserInterfaceStyle userInterfaceStyle;
@property (nonatomic) BOOL statusBarVisible;
@property (nonatomic) UIStatusBarStyle statusBarStyle;
@property (nonatomic) UIStatusBarAnimation statusBarAnimation;
@property (nonatomic, readonly, strong) UIViewController * _Nullable viewController;
@property (nonatomic, strong) CAPInstanceConfiguration * _Nonnull config;
- (WKWebView * _Nullable)getWebView SWIFT_WARN_UNUSED_RESULT;
- (BOOL)isSimulator SWIFT_WARN_UNUSED_RESULT;
- (BOOL)isDevMode SWIFT_WARN_UNUSED_RESULT;
- (BOOL)getStatusBarVisible SWIFT_WARN_UNUSED_RESULT;
- (UIStatusBarStyle)getStatusBarStyle SWIFT_WARN_UNUSED_RESULT;
- (UIUserInterfaceStyle)getUserInterfaceStyle SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getLocalUrl SWIFT_WARN_UNUSED_RESULT;
- (void)setServerBasePath:(NSString * _Nonnull)path;
- (void)registerPluginType:(SWIFT_METATYPE(CAPPlugin) _Nonnull)pluginType;
- (void)registerPluginInstance:(CAPPlugin * _Nonnull)pluginInstance;
- (CAPPlugin * _Nullable)pluginWithName:(NSString * _Nonnull)withName SWIFT_WARN_UNUSED_RESULT;
- (void)saveCall:(CAPPluginCall * _Nonnull)call;
- (CAPPluginCall * _Nullable)savedCallWithID:(NSString * _Nonnull)withID SWIFT_WARN_UNUSED_RESULT;
- (void)releaseCall:(CAPPluginCall * _Nonnull)call;
- (void)releaseCallWithID:(NSString * _Nonnull)withID;
- (CAPPluginCall * _Nullable)getSavedCall:(NSString * _Nonnull)callbackId SWIFT_WARN_UNUSED_RESULT;
- (void)releaseCallWithCallbackId:(NSString * _Nonnull)callbackId;
- (void)evalWithPlugin:(CAPPlugin * _Nonnull)plugin js:(NSString * _Nonnull)js;
- (void)evalWithJs:(NSString * _Nonnull)js;
- (void)triggerJSEventWithEventName:(NSString * _Nonnull)eventName target:(NSString * _Nonnull)target;
- (void)triggerJSEventWithEventName:(NSString * _Nonnull)eventName target:(NSString * _Nonnull)target data:(NSString * _Nonnull)data;
- (void)triggerWindowJSEventWithEventName:(NSString * _Nonnull)eventName;
- (void)triggerWindowJSEventWithEventName:(NSString * _Nonnull)eventName data:(NSString * _Nonnull)data;
- (void)triggerDocumentJSEventWithEventName:(NSString * _Nonnull)eventName;
- (void)triggerDocumentJSEventWithEventName:(NSString * _Nonnull)eventName data:(NSString * _Nonnull)data;
/// Translate a URL from the web view into a file URL for native iOS.
/// The web view may be handling several different types of URLs:
/// <ul>
///   <li>
///     res:// (shortcut scheme to web assets)
///   </li>
///   <li>
///     file:// (fully qualified URL to file on the local device)
///   </li>
///   <li>
///     base64:// (to be implemented)
///   </li>
///   <li>
///   </li>
/// </ul>
- (NSURL * _Nullable)localURLFromWebURL:(NSURL * _Nullable)webURL SWIFT_WARN_UNUSED_RESULT;
/// Translate a file URL for native iOS into a URL to load in the web view.
- (NSURL * _Nullable)portablePathFromLocalURL:(NSURL * _Nullable)localURL SWIFT_WARN_UNUSED_RESULT;
- (void)showAlertWithTitle:(NSString * _Nonnull)title message:(NSString * _Nonnull)message buttonTitle:(NSString * _Nonnull)buttonTitle;
- (void)presentVC:(UIViewController * _Nonnull)viewControllerToPresent animated:(BOOL)flag completion:(void (^ _Nullable)(void))completion;
- (void)dismissVCWithAnimated:(BOOL)flag completion:(void (^ _Nullable)(void))completion;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class NSURLSession;
@class NSURLSessionTask;
@class NSHTTPURLResponse;
@class NSURLRequest;

SWIFT_CLASS("_TtC9Capacitor19CapacitorUrlRequest")
@interface CapacitorUrlRequest : NSObject <NSURLSessionTaskDelegate>
- (void)URLSession:(NSURLSession * _Nonnull)session task:(NSURLSessionTask * _Nonnull)task willPerformHTTPRedirection:(NSHTTPURLResponse * _Nonnull)response newRequest:(NSURLRequest * _Nonnull)request completionHandler:(void (^ _Nonnull)(NSURLRequest * _Nullable))completionHandler;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class WKHTTPCookieStore;

SWIFT_CLASS("_TtC9Capacitor25CapacitorWKCookieObserver")
@interface CapacitorWKCookieObserver : NSObject <WKHTTPCookieStoreObserver>
- (void)cookiesDidChangeInCookieStore:(WKHTTPCookieStore * _Nonnull)cookieStore;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class PluginConfig;

@interface CAPInstanceConfiguration (SWIFT_EXTENSION(Capacitor))
@property (nonatomic, readonly, copy) NSURL * _Nonnull appStartFileURL;
@property (nonatomic, readonly, copy) NSURL * _Nonnull appStartServerURL;
@property (nonatomic, readonly, copy) NSURL * _Nullable errorPathURL;
- (id _Nullable)getPluginConfigValue:(NSString * _Nonnull)pluginId :(NSString * _Nonnull)configKey SWIFT_WARN_UNUSED_RESULT SWIFT_DEPRECATED_MSG("Use getPluginConfig");
- (PluginConfig * _Nonnull)getPluginConfig:(NSString * _Nonnull)pluginId SWIFT_WARN_UNUSED_RESULT;
- (BOOL)shouldAllowNavigationTo:(NSString * _Nonnull)host SWIFT_WARN_UNUSED_RESULT;
- (id _Nullable)getValue:(NSString * _Nonnull)key SWIFT_WARN_UNUSED_RESULT SWIFT_DEPRECATED_MSG("Use direct property accessors");
- (NSString * _Nullable)getString:(NSString * _Nonnull)key SWIFT_WARN_UNUSED_RESULT SWIFT_DEPRECATED_MSG("Use direct property accessors");
@end



@interface CAPInstanceDescriptor (SWIFT_EXTENSION(Capacitor))
@property (nonatomic, readonly) BOOL cordovaDeployDisabled;
- (void)normalize;
@end


@interface NSNotification (SWIFT_EXTENSION(Capacitor))
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSNotificationName _Nonnull capacitorOpenURL;)
+ (NSNotificationName _Nonnull)capacitorOpenURL SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSNotificationName _Nonnull capacitorOpenUniversalLink;)
+ (NSNotificationName _Nonnull)capacitorOpenUniversalLink SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSNotificationName _Nonnull capacitorContinueActivity;)
+ (NSNotificationName _Nonnull)capacitorContinueActivity SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSNotificationName _Nonnull capacitorDidRegisterForRemoteNotifications;)
+ (NSNotificationName _Nonnull)capacitorDidRegisterForRemoteNotifications SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSNotificationName _Nonnull capacitorDidFailToRegisterForRemoteNotifications;)
+ (NSNotificationName _Nonnull)capacitorDidFailToRegisterForRemoteNotifications SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSNotificationName _Nonnull capacitorDecidePolicyForNavigationAction;)
+ (NSNotificationName _Nonnull)capacitorDecidePolicyForNavigationAction SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSNotificationName _Nonnull capacitorStatusBarTapped;)
+ (NSNotificationName _Nonnull)capacitorStatusBarTapped SWIFT_WARN_UNUSED_RESULT;
@end



@class UNNotification;
@class UNNotificationResponse;

SWIFT_PROTOCOL_NAMED("NotificationHandlerProtocol")
@protocol CAPNotificationHandlerProtocol
- (UNNotificationPresentationOptions)willPresentWithNotification:(UNNotification * _Nonnull)notification SWIFT_WARN_UNUSED_RESULT;
- (void)didReceiveWithResponse:(UNNotificationResponse * _Nonnull)response;
@end

@class UNUserNotificationCenter;

SWIFT_CLASS_NAMED("NotificationRouter")
@interface CAPNotificationRouter : NSObject <UNUserNotificationCenterDelegate>
- (void)userNotificationCenter:(UNUserNotificationCenter * _Nonnull)center willPresentNotification:(UNNotification * _Nonnull)notification withCompletionHandler:(void (^ _Nonnull)(UNNotificationPresentationOptions))completionHandler;
- (void)userNotificationCenter:(UNUserNotificationCenter * _Nonnull)center didReceiveNotificationResponse:(UNNotificationResponse * _Nonnull)response withCompletionHandler:(void (^ _Nonnull)(void))completionHandler;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC9Capacitor12PluginConfig")
@interface PluginConfig : NSObject
- (NSString * _Nullable)getString:(NSString * _Nonnull)configKey :(NSString * _Nullable)defaultValue SWIFT_WARN_UNUSED_RESULT;
- (BOOL)getBoolean:(NSString * _Nonnull)configKey :(BOOL)defaultValue SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)getInt:(NSString * _Nonnull)configKey :(NSInteger)defaultValue SWIFT_WARN_UNUSED_RESULT;
- (BOOL)isEmpty SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end




@protocol WKURLSchemeTask;

SWIFT_CLASS_NAMED("WebViewAssetHandler")
@interface CAPWebViewAssetHandler : NSObject <WKURLSchemeHandler>
- (void)webView:(WKWebView * _Nonnull)webView startURLSchemeTask:(id <WKURLSchemeTask> _Nonnull)urlSchemeTask;
- (void)webView:(WKWebView * _Nonnull)webView stopURLSchemeTask:(id <WKURLSchemeTask> _Nonnull)urlSchemeTask;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class WKNavigation;
@class WKSecurityOrigin;
@class WKFrameInfo;
@class WKNavigationAction;
@class WKUserContentController;
@class WKScriptMessage;
@class WKWebViewConfiguration;
@class WKWindowFeatures;
@class UIScrollView;
@class UIView;

SWIFT_CLASS_NAMED("WebViewDelegationHandler")
@interface CAPWebViewDelegationHandler : NSObject <UIScrollViewDelegate, WKNavigationDelegate, WKScriptMessageHandler, WKUIDelegate>
- (void)webView:(WKWebView * _Nonnull)webView didStartProvisionalNavigation:(WKNavigation * _Null_unspecified)navigation;
- (void)webView:(WKWebView * _Nonnull)webView requestMediaCapturePermissionForOrigin:(WKSecurityOrigin * _Nonnull)origin initiatedByFrame:(WKFrameInfo * _Nonnull)frame type:(WKMediaCaptureType)type decisionHandler:(void (^ _Nonnull)(WKPermissionDecision))decisionHandler SWIFT_AVAILABILITY(ios,introduced=15);
- (void)webView:(WKWebView * _Nonnull)webView requestDeviceOrientationAndMotionPermissionForOrigin:(WKSecurityOrigin * _Nonnull)origin initiatedByFrame:(WKFrameInfo * _Nonnull)frame decisionHandler:(void (^ _Nonnull)(WKPermissionDecision))decisionHandler SWIFT_AVAILABILITY(ios,introduced=15);
- (void)webView:(WKWebView * _Nonnull)webView decidePolicyForNavigationAction:(WKNavigationAction * _Nonnull)navigationAction decisionHandler:(void (^ _Nonnull)(WKNavigationActionPolicy))decisionHandler;
- (void)webView:(WKWebView * _Nonnull)webView didFinishNavigation:(WKNavigation * _Null_unspecified)navigation;
- (void)webView:(WKWebView * _Nonnull)webView didFailNavigation:(WKNavigation * _Null_unspecified)navigation withError:(NSError * _Nonnull)error;
- (void)webView:(WKWebView * _Nonnull)webView didFailProvisionalNavigation:(WKNavigation * _Null_unspecified)navigation withError:(NSError * _Nonnull)error;
- (void)webViewWebContentProcessDidTerminate:(WKWebView * _Nonnull)webView;
- (void)userContentController:(WKUserContentController * _Nonnull)userContentController didReceiveScriptMessage:(WKScriptMessage * _Nonnull)message;
- (void)webView:(WKWebView * _Nonnull)webView runJavaScriptAlertPanelWithMessage:(NSString * _Nonnull)message initiatedByFrame:(WKFrameInfo * _Nonnull)frame completionHandler:(void (^ _Nonnull)(void))completionHandler;
- (void)webView:(WKWebView * _Nonnull)webView runJavaScriptConfirmPanelWithMessage:(NSString * _Nonnull)message initiatedByFrame:(WKFrameInfo * _Nonnull)frame completionHandler:(void (^ _Nonnull)(BOOL))completionHandler;
- (void)webView:(WKWebView * _Nonnull)webView runJavaScriptTextInputPanelWithPrompt:(NSString * _Nonnull)prompt defaultText:(NSString * _Nullable)defaultText initiatedByFrame:(WKFrameInfo * _Nonnull)frame completionHandler:(void (^ _Nonnull)(NSString * _Nullable))completionHandler;
- (WKWebView * _Nullable)webView:(WKWebView * _Nonnull)webView createWebViewWithConfiguration:(WKWebViewConfiguration * _Nonnull)configuration forNavigationAction:(WKNavigationAction * _Nonnull)navigationAction windowFeatures:(WKWindowFeatures * _Nonnull)windowFeatures SWIFT_WARN_UNUSED_RESULT;
- (void)scrollViewWillBeginZooming:(UIScrollView * _Nonnull)scrollView withView:(UIView * _Nullable)view;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
