
target 'Capacitor' do
  use_frameworks!
  pod 'CapacitorCordova', :path => '../../'
  pod 'GCDWebServer', '~> 3.0', :inhibit_warnings => true
  target 'CapacitorTests' do
    inherit! :search_paths
    
  end

end
