# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
source 'https://github.com/ionic-team/Specs'

target 'IonicRunner' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for IonicRunner
  pod 'Avocado', :path => '../../../ios/Avocado'
end
