name: Attach .xcframework file to release

on: workflow_dispatch
jobs:
  publish-xcframework:
    runs-on: macos-11
    timeout-minutes: 30
    steps:
      - run: sudo xcode-select --switch /Applications/Xcode_12.5.app
      - run: brew install ghr
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: native-publish
      - name: Build Capacitor.xcframework
        run: carthage build --no-skip-current --use-xcframeworks
      - name: Build CapacitorCordova.xcframework
        run: |
          cd ios/CapacitorCordova
          xcodebuild archive -scheme Cordova -sdk iphonesimulator SKIP_INSTALL=NO -archivePath Build/iOS-Simulator
          xcodebuild archive -scheme Cordova -sdk iphoneos SKIP_INSTALL=NO -archivePath Build/iOS 
          xcodebuild -create-xcframework -framework Build/iOS.xcarchive/Products/Library/Frameworks/Cordova.framework -framework Build/iOS-Simulator.xcarchive/Products/Library/Frameworks/Cordova.framework -output CapacitorCordova.xcframework
          cd ../..
      - name: Create Capacitor.xcframework.zip
        run: |
          mkdir Carthage/Build/CapacitorCordova.xcframework
          mv ios/CapacitorCordova/CapacitorCordova.xcframework/* Carthage/Build/CapacitorCordova.xcframework
          zip -r Capacitor.xcframework.zip Carthage/Build
          rm -rf ios/CapacitorCordova/CapacitorCordova.xcframework
      - name: Attach ZIP to latest release
        run: ghr -t ${{ secrets.GITHUB_TOKEN }} -replace $(git describe --tags --abbrev=0) Capacitor.xcframework.zip
