name: Attach .xcframework file to release

on: workflow_dispatch
jobs:
  publish-xcframework:
    runs-on: macos-11
    timeout-minutes: 30
    steps:
      - run: sudo xcode-select --switch /Applications/Xcode_12.5.app
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - uses: actions/checkout@v2
        with:
          ref: native-publish
      - name: Build .xcframework file
        run: echo "Hello World"
